#
# Conditional build:
%bcond_without	static_libs	# static library
#
Summary:	DockApp Making Standard Library
Summary(pl.UTF-8):	Biblioteka do tworzenia dokowalnych aplikacji
Summary(pt_BR.UTF-8):	Biblioteca para desenvolver aplicativos dock
Name:		libdockapp
Version:	0.7.3
Release:	1
License:	MIT
Group:		X11/Libraries
Source0:	https://www.dockapps.net/download/%{name}-%{version}.tar.gz
# Source0-md5:	7b029c2b2542d1974085690427354501
URL:		https://www.dockapps.net/libdockapp
BuildRequires:	autoconf >= 2.59
BuildRequires:	automake
BuildRequires:	libtool >= 2:2
BuildRequires:	pkgconfig
BuildRequires:	xorg-font-font-util >= 1.1
BuildRequires:	xorg-lib-libX11-devel
BuildRequires:	xorg-lib-libXext-devel
BuildRequires:	xorg-lib-libXpm-devel
Requires(post,postun):	/sbin/ldconfig
Requires(post,postun):	fontpostinst
Requires:	%{_fontsdir}/misc
Obsoletes:	docklib < 0.3
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
DockApp Making Standard Library.

%description -l pl.UTF-8
Standardowa biblioteka do tworzenia dokowalnych aplikacji.

%description -l pt_BR.UTF-8
Esta biblioteca provê um início básico para o desenvolvimento de
aplicativos dock.

%package devel
Summary:	Header files etc to develop DockApps
Summary(pl.UTF-8):	Pliki nagłówkowe i inne do tworzenia dokowalnych aplikacji
Summary(pt_BR.UTF-8):	Arquivos de desenvolvimento para a libdockapp
Group:		X11/Development/Libraries
Requires:	%{name} = %{version}-%{release}
Requires:	xorg-lib-libX11-devel
Requires:	xorg-lib-libXext-devel
Requires:	xorg-lib-libXpm-devel

%description devel
Header files etc to develop DockApps.

%description devel -l pl.UTF-8
Pliki nagłówkowe i inne niezbędne do tworzenia dokowalnych aplikacji w
oparciu o tę bibliotekę.

%description devel -l pt_BR.UTF-8
Arquivo de cabeçalho e bibliotecas de desenvolvimento para a
libdockapp

%package static
Summary:	Static libdockapp library
Summary(pl.UTF-8):	Biblioteka statyczna libdockapp
Summary(pt_BR.UTF-8):	Bibliotecas estáticas para desenvolvimento com libdockapp
Group:		X11/Development/Libraries
Requires:	%{name}-devel = %{version}-%{release}

%description static
Static libdockapp library.

%description static -l pl.UTF-8
Biblioteka statyczna libdockapp.

%description static -l pt_BR.UTF-8
Bibliotecas estáticas para desenvolvimento com libdockapp

%prep
%setup -q

%build
%{__libtoolize}
%{__aclocal}
%{__autoconf}
%{__automake}
%configure \
	--without-examples \
	%{!?with_static_libs:--disable-static}

%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_examplesdir}/%{name}-%{version}

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

# obsoleted by pkg-config
%{__rm} $RPM_BUILD_ROOT%{_libdir}/libdockapp.la

cp -rf examples/[br]* $RPM_BUILD_ROOT%{_examplesdir}/%{name}-%{version}

# fonts.dir is regenerated by fontpostinst
%{__rm} $RPM_BUILD_ROOT%{_fontsdir}/misc/fonts.dir

%clean
rm -rf $RPM_BUILD_ROOT

%post
/sbin/ldconfig
fontpostinst misc

%postun
/sbin/ldconfig
fontpostinst misc

%files
%defattr(644,root,root,755)
%doc README AUTHORS NEWS ChangeLog
%{_libdir}/libdockapp.so.*.*.*
%ghost %{_libdir}/libdockapp.so.3
%{_fontsdir}/misc/luxel-ascii-*.pcf.gz
%{_fontsdir}/misc/seg7-ascii-*.pcf.gz

%files devel
%defattr(644,root,root,755)
%{_libdir}/libdockapp.so
%{_includedir}/libdockapp
%{_pkgconfigdir}/dockapp.pc
%{_examplesdir}/%{name}-%{version}

%if %{with static_libs}
%files static
%defattr(644,root,root,755)
%{_libdir}/libdockapp.a
%endif
